# Site settings
title: The Classic Yuppie on Github
email: john@classicyuppie.com
description: > # this means to ignore newlines until "baseurl:"
  Tech evangelist and blogger. Mac enthusiast. I crave delicious design. Never fear being wrong.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://classicyuppie.github.io" # the base hostname & protocol for your site
twitter_username: classicyuppie
github_username:  classicyuppie

# Build settings
markdown: kramdown

highlighter: pygments
github: [Repository metadata]
